feature(wc_yotpo.php): created possibility of v3 widgets usage
YotpoLtd/woocommerce-plugin-yotpo-reviews pull request #38
Opened 2023-04-14 14:01 UTC by p-bartosz

2023-07-12 05:57 UTC, LiorGingi requested changes

2023-07-12 05:57 UTC, LiorGingi commented on trunk/wc_yotpo.php
> +	$reviews_widget_id = $yotpo_settings['reviews_widget_id'];
Why do you get the widget ID here? should be part of the `generate_v3_reviews_widget_code` method.

2023-07-12 05:57 UTC, LiorGingi commented on trunk/wc_yotpo.php
> +	$qna_widget_id = $yotpo_settings['qna_widget_id'];
Getting the widget ID should be part of the `generate_v3_qna_widget_code` method.

2023-07-12 05:57 UTC, LiorGingi commented on trunk/wc_yotpo.php
> +	}
Why return? don't we want to show the Q&A bottomline for V3 customers?

2023-07-12 05:57 UTC, LiorGingi commented on trunk/wc_yotpo.php
> +	$reviews_widget_id = $yotpo_settings['reviews_widget_id'];
Star rating getting reviews widget ID?

2023-07-12 05:57 UTC, LiorGingi commented on trunk/wc_yotpo.php
> +				'ratings_widget_id' => '',
The indentation seems wrong here.

2023-07-12 05:57 UTC, LiorGingi commented on trunk/templates/wc-yotpo-settings.php
>                         <th scope='row'><div>Synchronise the widgets' codes:</div></th>
Did this wording go through your PM?

2023-07-12 05:57 UTC, LiorGingi commented on trunk/templates/wc-yotpo-settings.php
> +                       <td><input type='submit' name='yotpo_remove_ids' value='Reset' class='button-secondary' id='yotpo_remove_ids'/></td>
Why should they remove it? Checking out the checkout should revert them to V2, shouldn't it?

2023-07-12 05:57 UTC, LiorGingi commented on trunk/wc_yotpo.php
> +	if (!$use_v3_widgets) {
Are there any further cases where nothing will be returned over here?
If not, this if statement is redundant.

2023-07-13 14:02 UTC, p-bartosz commented
@LiorGingi left one comment
all the rest is outdated

2023-07-19 20:59 UTC, LiorGingi approved these changes

2023-07-19 20:59 UTC, merged