update(wcYotpo): supporting HOPS: using CRUD API in the submit past o…
YotpoLtd/woocommerce-plugin-yotpo-reviews pull request #52
Opened 2023-08-15 23:21 UTC by sharp80

…rder feature

2023-08-16 18:09 UTC, LiorGingi requested changes

2023-08-17 12:00 UTC, sharp80 commented on trunk/wc_yotpo.php
> +	}
this line is telling WC that we support HPOS (once upon a time HPOS name was custom order table :) )

2023-08-17 12:02 UTC, sharp80 commented on trunk/wc_yotpo.php
> +	} else {
CRUD objects were introduced in WC 3.0.
HPOS utilization is abstacted by CRUD - the only thing you need to use is to actually utilize CRUD - and not try to run SQL on top of tables which we did. BUT - if you are using WC < 3.0 - you cannot utilize CRUD. So my code is not about HPOS at all -> its about using CRUD.

2023-08-22 07:23 UTC, LiorGingi approved these changes

2023-08-22 17:52 UTC, merged